version: "3.8"

services:
  db:
    image: postgres:14
    container_name: ecomm-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: ecommerce-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce
      DB_DIALECT: postgres
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads  # ✅ This syncs local `uploads` with container `/app/uploads`

volumes:
  pgdata: {}
